name: Convert Markdown to HTML
on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
      - name: Convert README.md to HTML
        run: |
          pandoc docs/aoa.md -o docs/index.html
      - name: Commit and push changes
        run: |
          git config --local user.name "kevinlee-06"
          git config --local user.email "cgshyuankai@proton.me"
          git add docs/index.html
          git commit -m "Build: 201 Created" || echo "Build: 304 Not Modified"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
