name: Convert Markdown to HTML
on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
      - name: Convert README.md to HTML
        run: |
          pandoc docs/aoa.md -o docs/index.html
      - name: Commit and push changes
        run: |
          git config --local user.name "許景企鵝"
          git config --local user.email "penguin-joyce@ntut.club"
          git add docs/index.html
          git commit -m "景夾已從 /docs/aoa.md 構建新的 /docs/index.html" || echo "景夾表示沒有改變"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
